baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "beautifulhugo"

    
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1


[[menu.main]]
  identifier = "about"
  name = "About Page"
  url = "/about/"
  weight = 2 


[[menu.main]]
  identifier = "articles"
  name = "Article Essays"
  url = "/articles/"
  weight = 3 


[[menu.main]]
  identifier = "blog"
  name = "My Blogs!"
  url = "/blog/"
  weight = 40

    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

